export const SocketEvents = {
	ERROR: "error",
	NOTIFICATION: "notification",
	JOIN_MATCH_ROOM: "join_match_room",
	LEAVE_MATCH_ROOM: "leave_match_room",
	MATCH_DELETED: "match_deleted",
	UPDATE_MATCH_STATE: "update_match_state",
	UPDATE_MATCH_SESSION: "update_match_session",
	UPDATE_MATCH_TIMER_INPUTS: "update_match_timer_inputs",
	SAVE_MATCH_TIMER_INPUTS: "save_match_timer_inputs",
	MATCH_STARTED: "match_started",
	MATCH_COMPLETED: "match_completed",
	MATCH_UPDATED: "match_updated",
	PAUSE_MATCH: "pause_match",
	RESUME_MATCH: "resume_match",
	UNDO_DRAFT_ACTION: "undo_draft_action",
} as const;
