services:
  xabyss_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - xabyss_db_vol:/var/lib/mysql
    networks:
      - xabyss_net

networks:
  xabyss_net:
    name: xabyss_net
    driver: bridge

volumes:
  xabyss_db_vol:
