export const TableNames = {
	Sample: "sample",
	Account: "account",
	AccountCharacter: "account_character",
	StaffRole: "staff_role",
	Permission: "permission",
	StaffRolePermission: "staff_role_permission",
	Character: "character",
	Weapon: "weapon",
	CharacterCost: "character_cost",
	CostMilestone: "cost_milestone",
	WeaponCost: "weapon_cost",
	CharacterLevelCost: "character_level_cost",
	Notification: "notification",
	Match: "match",
	MatchSession: "match_session",
	MatchState: "match_state",
	BanPickSlot: "ban_pick_slot",
	SessionCost: "session_cost",
	SessionRecord: "session_record",
	CharacterWeapon: "character_weapon",
};

export const ColumnNames = {
	Global: {
		createdAt: "created_at",
		updatedAt: "updated_at",
		createdById: "created_by_id",
		updatedById: "updated_by_id",
		isActive: "is_active",
	},
	Sample: {
		id: "sample_id",
		name: "sample_name",
		age: "sample_age",
	},
	Account: {
		id: "account_id",
		ingameUuid: "ingame_uuid",
		email: "email",
		displayName: "display_name",
		password: "password",
		lastLoginAt: "last_login_at",
		role: "role",
		avatar: "avatar",
	},
	AccountCharacter: {
		id: "account_character_id",
		accountId: "account_id",
		characterId: "character_id",
		activatedConstellation: "activated_constellation",
		characterLevel: "character_level",
		notes: "notes",
	},
	StaffRole: {
		id: "staff_role_id",
		name: "staff_role_name",
	},
	Permission: {
		id: "permission_id",
		description: "permission_description",
		code: "permission_code",
		deprecated: "permission_deprecated",
	},
	StaffRolePermission: {
		id: "staff_role_permission_id",
	},
	Character: {
		id: "character_id",
		key: "character_key",
		name: "character_name",
		element: "character_element",
		weaponType: "character_weapon_type",
		rarity: "character_rarity",
		iconUrl: "character_icon_url",
	},
	Weapon: {
		id: "weapon_id",
		key: "weapon_key",
		name: "weapon_name",
		type: "weapon_type",
		rarity: "weapon_rarity",
		iconUrl: "weapon_icon_url",
	},
	CharacterCost: {
		id: "character_cost_id",
		cost: "character_cost",
		constellation: "character_constellation",
	},
	CostMilestone: {
		id: "cost_milestone_id",
		costFrom: "cost_from",
		costTo: "cost_to",
		secPerCost: "sec_per_cost",
	},
	WeaponCost: {
		id: "weapon_cost_id",
		weaponRarity: "weapon_rarity",
		unit: "unit",
		value: "value",
		upgradeLevel: "upgrade_level",
	},
	CharacterLevelCost: {
		id: "character_level_cost_id",
		characterId: "character_id",
		level: "character_level",
		cost: "level_cost",
	},
	Notification: {
		id: "notification_id",
		type: "notification_type",
		content: "notification_content",
		isRead: "is_read",
	},
	Match: {
		id: "match_id",
		hostId: "host_id",
		sessionCount: "session_count",
		type: "match_type",
		status: "match_status",
		redPlayerId: "red_player_id",
		bluePlayerId: "blue_player_id",
	},
	MatchSession: {
		id: "match_session_id",
		sessionIndex: "session_index",
		redParticipantId: "red_participant_id",
		blueParticipantId: "blue_participant_id",
		currentTurn: "current_turn",
		totalCostBlue: "total_cost_blue",
		totalCostRed: "total_cost_red",
		sessionStatus: "session_status",
	},
	MatchState: {
		id: "match_state_id",
		host_joined: "host_joined",
		red_player_joined: "red_player_joined",
		blue_player_joined: "blue_player_joined",
		currentSession: "current_session",
		currentTurn: "current_turn",
		blueBanChars: "blue_ban_chars",
		blueSelectedChars: "blue_selected_chars",
		blueSelectedWeapons: "blue_selected_weapons",
		redBanChars: "red_ban_chars",
		redSelectedChars: "red_selected_chars",
		redSelectedWeapons: "red_selected_weapons",
		blueTimeBank: "blue_time_bank",
		redTimeBank: "red_time_bank",
		turnStartedAt: "turn_started_at",
		draftStep: "draft_step",
		blueSupachaiUsedCount: "blue_supachai_used_count",
		redSupachaiUsedCount: "red_supachai_used_count",
		blueSupachaiUsedSessionCount: "blue_supachai_used_session_count",
		redSupachaiUsedSessionCount: "red_supachai_used_session_count",
		blueUsedChars: "blue_used_chars",
		redUsedChars: "red_used_chars",
		supachaiMaxUses: "supachai_max_uses",
	},
	BanPickSlot: {
		id: "ban_pick_slot_id",
		matchSessionId: "match_session_id",
		turnIndex: "turn_index",
		teamOrder: "team_order",
		slotType: "slot_type",
		matchSide: "match_side",
		slotStatus: "slot_status",
		characterId: "character_id",
		weaponId: "weapon_id",
		weaponRefinement: "weapon_refinement",
		selectedByAccountId: "selected_by_account_id",
		locketAt: "locked_at",
		weaponSelectedAt: "weapon_selected_at",
	},
	SessionCost: {
		id: "session_cost_id",
		matchSessionId: "match_session_id",
		blueTotalCost: "blue_total_cost",
		blueCostMilestone: "blue_cost_milestone",
		blueConstellationCost: "blue_constellation_cost",
		blueRefinementCost: "blue_refinement_cost",
		blueLevelCost: "blue_level_cost",
		blueTimeBonusCost: "blue_time_bonus_cost",
		redTotalCost: "red_total_cost",
		redCostMilestone: "red_cost_milestone",
		redConstellationCost: "red_constellation_cost",
		redRefinementCost: "red_refinement_cost",
		redLevelCost: "red_level_cost",
		redTimeBonusCost: "red_time_bonus_cost",
	},
	SessionRecord: {
		id: "session_record_id",
		matchSessionId: "match_session_id",
		blueChamber1: "blue_chamber_1",
		blueChamber2: "blue_chamber_2",
		blueChamber3: "blue_chamber_3",
		blueResetTimes: "blue_reset_times",
		blueFinalTime: "blue_final_time",
		redChamber1: "red_chamber_1",
		redChamber2: "red_chamber_2",
		redChamber3: "red_chamber_3",
		redResetTimes: "red_reset_times",
		redFinalTime: "red_final_time",
	},
	CharacterWeapon: {
		id: "character_weapon_id",
		characterId: "character_id",
		weaponId: "weapon_id",
		constellationCondition: "constellation_condition",
	},
};

export const IndexNames = {
	Sample: {
		age: "idx_sample_sample_age",
	},
	Account: {
		role: "idx_account_role",
		isActive: "idx_account_is_active",
		roleIsActive: "idx_account_role_is_active",
		ingameUuid: "idx_account_ingame_uuid",
	},
	AccountCharacter: {
		accountIdCharacterId: "idx_account_character_account_id_character_id",
		characterId: "idx_account_character_character_id",
	},
	Character: {
		element: "idx_character_element",
		weaponType: "idx_character_weapon_type",
		rarity: "idx_character_rarity",
		isActive: "idx_character_is_active",
	},
	Weapon: {
		type: "idx_weapon_type",
		rarity: "idx_weapon_rarity",
		isActive: "idx_weapon_is_active",
	},
	CharacterLevelCost: {
		characterIdLevel: "idx_character_level_cost_character_id_level",
	},
	StaffRole: {
		isActive: "idx_staff_role_is_active",
	},
	StaffRolePermission: {
		staffRoleId: "idx_staff_role_permission_staff_role_id",
		permissionId: "idx_staff_role_permission_permission_id",
		staffRolePermission: "idx_staff_role_permission_composite",
	},
	Permission: {
		deprecated: "idx_permission_deprecated",
	},
	Match: {
		hostId: "idx_match_host_id",
		redPlayerId: "idx_match_red_player_id",
		bluePlayerId: "idx_match_blue_player_id",
		createdAt: "idx_match_created_at",
	},
	MatchSession: {
		matchId: "idx_match_session_match_id",
		redParticipantId: "idx_match_session_red_participant_id",
		blueParticipantId: "idx_match_session_blue_participant_id",
	},
	MatchState: {
		matchId: "uq_match_state_match_id",
	},
};
